esphome:
    name: enocean

esp32:
  board: esp32dev

wifi:
  ssid: "Kraftwerk_2G"
  password: "7JcQPDfkmBBNESvWkKnv"

ota:

api:

web_server:

logger:
  level: verbose

uart:
  tx_pin: 17
  rx_pin: 16
  baud_rate: 57600


binary_sensor:
  - platform: enocean
    address: [0xfe, 0xea, 0x72, 0x79]
    # name: "sdf"

# wiegand:
#   - id: mykeypad
#     d0: GPIO16
#     d1: GPIO17
#     on_key:
#       - lambda: ESP_LOGI("KEY", "received key %d", x);
#     on_tag:
#       - lambda: ESP_LOGI("TAG", "received tag %s", x.c_str());
#     on_raw:
#       - lambda: ESP_LOGI("RAW", "received raw %d bits, value %llx", bits, value);